swagger: "2.0"
info:
  description: "This is a microservice that creates, modifies, and retrieves user accounts"
  version: "1.0.0"
  title: "Account Service"
host: "127.0.0.1:5000"
basePath: "/"
tags:
- name: "user"
  description: "Operations on users"
schemes:
- "http"
paths:
  /create_user:
    post:
      tags:
      - "user"
      summary: Create new users
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "Created"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        "409":
          description: "User already exists"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
  /get_user/{username}:
    get:
      tags:
      - "user"
      summary: "Return user information"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: username
        type: string
        required: true
      responses:
        "200":
          description: "Ok"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
              user:
                $ref: "#/definitions/User"
        "404":
          description: "User not found"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
  /modify_user/{username}:
    put:
      tags:
      - "user"
      summary: "Modify user information"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: username
        type: string
        required: true
      - in: "body"
        name: "body"
        required: True
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Successful update"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        "400":
          description: "Bad request"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        "404":
          description: "User not found"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
definitions:
  User:
    type: "object"
    required:
      - username
      - hashed_passwd
      - isAdmin
    properties:
      username:
        type: "string"
      hashed_passwd:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      isAdmin:
        type: "boolean"
    xml:
      name: "User"